environment:
  global:
    TOXENV: py,codecov

  matrix:
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python35-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U tox

build: false

test_script:
  - python -m tox

cache:
  - '%LOCALAPPDATA%\pip\Cache'