environment:
  global:
    TOXENV: py,codecov

  matrix:
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python35-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:

  - python -m pip install -U tox
  - python -m pip install -U wheel

build_script:
  - python setup.py build

test_script:
  - python -m tox

after_test:
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi
  - ps: "ls dist"

artifacts:
  - path: dist\*

cache:
  - '%LOCALAPPDATA%\pip\Cache'