checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.6
    nodes:
      analysis:
        tests:
          override:
            - py-scrutinizer-run
      my-tests:
        dependencies:
          before:
            - pip install -r requirements-test.txt
            - python setup.py install
        tests:
          override:
            - coverage run --source=ebook_homebrew -m pytest --it
filter:
    excluded_paths:
        - 'tests/*'
        - 'doc_src/*'
        - 'docs/*'
    dependency_paths:
        - 'lib/*'