checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.6
    nodes:
      analysis:
        tests:
          override:
            - py-scrutinizer-run
filter:
    excluded_paths:
        - 'tests/*'
        - 'doc_src/*'
        - 'docs/*'
    dependency_paths:
        - 'lib/*'