checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.6
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
filter:
    excluded_paths:
        - 'tests/*'
        - 'doc_src/*'
        - 'docs/*'
    dependency_paths:
        - 'lib/*'