checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.6
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                        command: pylint-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'doc_src/*'
        - 'docs/*'
    dependency_paths:
        - 'lib/*'